"""Allowing nullable fields

Revision ID: 4c957d3792ef
Revises: 15cc5233db39
Create Date: 2020-11-07 12:27:56.566274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c957d3792ef'
down_revision = '15cc5233db39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecast', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('forecast', 'country',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('forecast', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('forecast', 'rain_precipitation',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('forecast', 'rain_probability',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('forecast', 'state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecast', 'state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('forecast', 'rain_probability',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('forecast', 'rain_precipitation',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('forecast', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('forecast', 'country',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('forecast', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
